export const routesConfig = {
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  homePage: "/",
  detaiProduct: "/detail/:id",
  products: "/products",
  seller: "/seller",
  myCart: "/myCart",
  pay: "/pay",
  blog: "/blog",
  notFound: "*",
  admin: "/admin",
  productAdmin: "/productadmin",
  createProduct: "/createProduct",
  editProduct: "/edit/:id",
  createCategory: "/createCategory",
  editCategory: "/editcategory/:id",
};
